Второе задание.
js-tasks-ru/js-20210615_yuliya309 pull request #2
Opened 2021-06-22 19:56 UTC by Qubear

2021-06-22 19:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-23 16:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-23 17:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-23 17:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-23 19:15 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-06-24 19:34 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for(let value of oldArray)
посмотрите пожалуйста решение которое мы разбирали на занятии.
что касается данного кода - следует избегать вложенных `if...else` конструкций, а также вложенных `break` и `continue` операторов - это очень сильно усложняет как чтение так и расширение кода

2021-06-24 19:34 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let newObj = {};
`const`

2021-06-24 19:35 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for(let value of fields)
в данном решении нет `let` мы не переприсваиваем ни одну переменную

2021-06-24 19:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        let arrayKey = path.split(".");
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-06-24 19:36 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        for(let key of arrayKey)
попробуйте упростить данный кусок кода: избавиться от лишних условий

2021-06-24 19:36 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    let newObj = {};
`const`

2021-06-24 19:36 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-06-25 07:24 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-06-25 12:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-25 13:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-06-25 13:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-06-25 16:20 UTC, dosandk approved these changes
good 👍

2021-06-25 16:20 UTC, merged